In [6]:
import os
import pandas as pd
import scipy
import scipy.io as scio

In [13]:
# 将新的标签存储为mat文件
# 加载标签、每年
for year in range(2012, 2018):
    data_root_bq = '/data/file/classification_data/2012-2019/'
    data_root = '/data/file/classification_data/years/'
    bq = pd.read_excel(os.path.join(data_root_bq+str(year), '标签1.xls'), header=None, index_col=0)
    data = scio.loadmat(os.path.join(data_root+str(year), 'X.mat'))['X']
    bq = bq.values
    print(bq)
    print(data)
    scipy.io.savemat(os.path.join(data_root+str(year), 'y.mat'), {'y': bq})


[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
[[ 2.61716000e-01  1.76241000e-01  1.94850000e-02 ...  2.06000000e+02
   5.39455000e-01  5.39455000e-01]
 [ 1.19902000e-01  3.12320000e-02  4.02220000e-02 ...  2.29000000e+02
  -7.14120000e-02 -6.95360000e-02]
 [ 8.03223000e-01  4.97520000e-02  4.23154000e-01 ...  2.42000000e+02
   2.95000000e-03  3.16500000e-03]
 ...
 [ 8.34997000e-01  7.31525000e-01  1.69830000e-02 ...  1.54000000e+02
   4.86557100e-03  5.46967564e-03]
 [ 6.54374000e-01  1.76659000e-01  1.60676000e-01 ...  8.70000000e+01
   4.86557100e-03  5.46967564e-03]
 [ 6.49724000e-01  2.44030000e-01  2.16358000e-01 ...  9.70000000e+01
   4.86557100e-03  5.46967564e-03]]
[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]
[[ 3.33203000e-01  2.33636000e-01  7.21000000e-03 ...  2.37000000e+02
   6.77539000e-01  6.77540000e-01]
 [ 1.54049000e-01  1.83340000e-02  3.05280000e-02 ...  2.37000000e+02
  -3.52000000e-04  4.84800000e-03]
 [ 9.63707000e-01  1.77110000e-01  4.65990000e-02 ...  1.00000000e+00
   5.0119000

In [8]:
year = 2012
data_root_bq = '/data/file/classification_data/2012-2019/'
data_root = '/data/file/classification_data/years/'
bq = pd.read_excel(os.path.join(data_root_bq+str(year), '标签1.xls'), header=None, index_col=0)
bq = bq.values
print(bq)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [12]:
bq = bq.reshape(-1)

In [ ]:
scipy.io.savemat(os.path.join(data_root+str(year), 'y.mat'), {'y': bq})